---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: check-merge-conflict
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-json
          - id: check-yaml
          - id: detect-private-key
          - id: check-added-large-files
            args: ['--maxkb=600']

    # ToDo: move this part to a different git hook
    # slows down commit
    - repo: https://github.com/gitguardian/gg-shield
      rev: v1.3.0
      hooks:
          - id: ggshield
            language_version: python3
            stages: [commit]
